name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Configure Git
        run: |
          git config core.quotepath false

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install uv && \
          python3 -m uv sync

      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ./.venv
          key: uv-${{ github.run_id }}
          restore-keys:
            uv-

      - name: Build the site
        run: |
          ./.venv/bin/sphinx-build --write-all template_sphinx build
          # TODO: Change `template_sphinx` to the source directory

      - name: Cache save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ./.venv
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
